import turtle

def draw_t(turtle_obj, start_x, start_y):
    turtle_obj.penup()
    turtle_obj.goto(start_x, start_y)
    turtle_obj.setheading(0)
    turtle_obj.pendown()
    turtle_obj.fillcolor("lightblue")
    turtle_obj.begin_fill()
    turtle_obj.forward(100)
    turtle_obj.right(90)
    turtle_obj.forward(15)
    turtle_obj.right(90)
    turtle_obj.forward(40)
    turtle_obj.left(90)
    turtle_obj.forward(85)
    turtle_obj.right(90)
    turtle_obj.forward(20)
    turtle_obj.right(90)
    turtle_obj.forward(85)
    turtle_obj.left(90)
    turtle_obj.forward(40)
    turtle_obj.right(90)
    turtle_obj.forward(15)
    turtle_obj.end_fill()

t = turtle.Turtle()
t.pensize(5)
draw_t(t, -280, 50)
turtle.done()